### PR TITLE
Release 0.14.24

### PR DESCRIPTION
**Pull request by FlorianRappl**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes

### Description

Fixes an issue with Node 17 with removed the support for the trailing slash notation on exports (only star exports work now).

Also added two props that have been demanded for a while on `ExtensionSlot`. Now the behavior of `empty` can be controlled a bit. Beforehand it always called `empty` and then `render`, now `render` may be discarded in case of a desired different envelop for `empty`. The `order` prop can be helpful, too, when `render` seems to powerful / too much work.

### Remarks

Potentially we'll also add support for `rush` as monorepo driver. Not sure yet.

### CODE REVIEW

**Review by manuelroemer — APPROVED** [review]
Looks great! 🚀 

The only thing I'd throw into the room is that I thought of perhaps renaming `noEmptyRender` to something like `skipCustomRenderWhenEmpty`? When I first looked at the test case above, `noEmptyRender`, without looking at the docs, made me think that nothing would be rendered when the slot is empty, i.e. that it might allow to conditionally hide the custom empty state in certain conditions. But maybe that's just me being weird... 😄

**Comment by FlorianRappl** [comment]
And I thought `noEmptyRender` is already long and clunky - but `skipCustomRenderWhenEmpty` brings it to the next level. I think the main issue is that the prop is called `render` - which is the same as the name of the process in general.

How about `emptySkipsRender`? Essentially thats also a description whats happening. Instead of rendering (or callling the `render` prop) we just take the output of `empty()`.

**Comment by manuelroemer** [comment]
> but `skipCustomRenderWhenEmpty` brings it to the next level.

Hehe, point taken - though I don't necessarily find long names bad if they make things clearer (at least with IntelliSense...).
But `emptySkipsRender` sounds nice!

> I think the main issue is that the prop is called render - which is the same as the name of the process in general.

That's why I thought about the `Custom` in the name above: To give a hint that this refers to the provided `render` function, not the rendering process in general. But I think that once you _do know_ what the props actually do, `render` is not a bad name for it.

**Review by manuelroemer — APPROVED** [review]
Awesome stuff, great to have a PNPM workaround mentioned already! 🚀

**Pull request merged**
