### PR TITLE
add documentation for a monorepo using rush

### PR DESCRIPTION
**Pull request by luckyluggi**
i might add another pr to describe some special things for adding blazor to the monorepo later

### CODE REVIEW

**Comment by luckyluggi** [comment]
Please dont complete this yet. I just noticed i miss one thing. :)

**Review by FlorianRappl — APPROVED** [review]
LGTM - thanks!

**Comment by luckyluggi** [comment]
ok. now it LGTM

**Comment by FlorianRappl** [comment]
The CLA assistant complains - can you check if the email address you used for committing is associated with your GitHub account? Thanks @luckyluggi !

**Comment by luckyluggi** [comment]
> The CLA assistant complains - can you check if the email address you used for committing is associated with your GitHub account? Thanks @luckyluggi !

oh. i did this on my work pc wher my work email is used. But since that work email has no github account i did the PR with my private account. What would be the best fix for that?

**Comment by FlorianRappl** [comment]
> But since that work email has no github account i did the PR with my private account. What would be the best fix for that?

You can associate multiple email addresses with your GitHub account. -> https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

Alternatively, you need to change the commits - you can just create a new branch from `documentation` and cherry pick the changes. Just make sure that the new / correct email address is associated when committing.

**Comment by luckyluggi** [comment]
ok i added the work email to my github account

**Comment by luckyluggi** [comment]
Then CLA thing still does not seem happy. i cant agree again because it says i already agreed

**Pull request merged**
