### PR TITLE
Update gen-plugins.js

### PR DESCRIPTION
**Pull request by carvinlo**
Missing the scope of package.

# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project
- [ ] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description

[Place a meaningful description here]

### Remarks

[Optionally place any follow-up comments, remarks, observations, or notes here for future reference]

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Can you elaborate where this plays a role? The documentation for the plugins seems to be generated just fine. Is there a problem somewhere?

**Comment by carvinlo** [comment]
Suppose a plugin package name is `@myscope/piral-cli-fetch`, but the generated document is `npm i piral-cli-fetch`.

**Comment by FlorianRappl** [comment]
OK so this is for potential future purposes and not to handle a current problem right?

**Comment by carvinlo** [comment]
Yeah, you are right.

**Pull request merged**
