### PR TITLE
Peer dependencies need to be valid as well. Fixes #341

### LINKED ISSUE #341: Submodule externals should not end up in peerDependencies
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Not relevant

## Description

Submodule externals (for example "redux-sage/effects") end up in the peerDependencies of a pilet. This causes issues with version-lens and with npm v7.

## Steps to Reproduce

1. Add a submodule to externals
2. Create/Upgrade pilet
3. see submodule appear in peerDependencies.

## Expected behavior

Submodules should not be added to peerDependencies.

## Actual behavior

Submodules do get added to peerDependencies.

## Possible Origin / Solution

Code to prevent this already exists for devDependencies, but not for peerDependencies.

### PR DESCRIPTION
**Pull request by SantoJambit**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [ ] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description

Submodules externals are not supposed to end up in the peerDependencies.

### CODE REVIEW

**Comment by SantoJambit** [comment]
tests fail locally, but they fail on develop branch as well, so that doesn't seem related to my changes.

**Comment by FlorianRappl** [comment]
Yeah that's right. I think we need a couple of unit tests for this to cover all cases. Also, right now a pilet determines what dependencies come in via its `peerDependencies`. This comes with a problem. Let's say I'd share `foo/bar`, but I don't share `foo`. Making it a valid peer dependency would lead to `foo`, which obviously is wrong.

**Comment by FlorianRappl** [comment]
> tests fail locally, but they fail on develop branch as well, so that doesn't seem related to my changes.

I don't think they fail online / in general (so it fails for you / your setup locally). It may be related to your Node / NPM version. Keep in mind that piral is developed with a different Node version using NPM 6. Let's see what we see here (which is where it counts).

**Comment by SantoJambit** [comment]
I've added tests for the rule. Not sure if it matches the code-style or test practices.
Will add tests for the other functionality when I get some time again.

**Comment by FlorianRappl** [comment]
> Not sure if it matches the code-style or test practices.

I think this is all fine - we can adjust / correct this later (when you have, e.g., the prettier extension for your editor it will just work / use the right style).

The thing that is blocking the merge right now is not the fix itself - this is great. Its that question what exactly to do with shared submodule dependencies. Right now the Piral CLI determines what to mark as shared dependencies when building a pilet by its `peerDependencies`. If we excluded the submodule (`foo/bar`) in there it will not be picked up. If we would include the full module (`foo`) then this may be wrong or lead to wrong results.

**Review by FlorianRappl — APPROVED** [review]
Let's merge it in to continue with the enhancements in `develop`. Thanks @SantoJambit for bringing this up and starting with a solution!

**Pull request merged**
