### PR TITLE
Added Angular 13 to piral-ng

### PR DESCRIPTION
**Pull request by daniel-rck**
# New Pull Request

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [ ] All new and existing tests passed

## Type(s) of Changes
Modified packages.json of ng-piral.

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description
Added Angular 13 to peerDependencies.

### CODE REVIEW

**Comment by FlorianRappl** [comment]
I am not sure what file `.vs/slnx.sqlite` is, but I think it should be removed.

Other than that: Is Angular 13 just working? Just changing the peer dependencies is one thing, but it should be compatible. Right now I don't know about that. Since the documentation wasn't updated either I am also not sure about the general process of supporting it.

Happy to merge, but we need to figure out if its working (and how) first. Thanks! :beers:

**Comment by daniel-rck** [comment]
> I am not sure what file `.vs/slnx.sqlite` is, but I think it should be removed.
> 
> Other than that: Is Angular 13 just working? Just changing the peer dependencies is one thing, but it should be compatible. Right now I don't know about that. Since the documentation wasn't updated either I am also not sure about the general process of supporting it.
> 
> Happy to merge, but we need to figure out if its working (and how) first. Thanks! 🍻

I think it is something related to Visual Studio. Removed :)

**Comment by FlorianRappl** [comment]
Hi @daniel-rck the file *.vs/slnx.sqlite* seems to be still there. Can you remove it please? Thanks!

**Comment by daniel-rck** [comment]
I removed the whole folder, as Visual Studio isn't needed anyway.

**Comment by FlorianRappl** [comment]
Superb thanks!

**Pull request merged**
